daysUntilClose: 14
responseRequiredLabel: needs information
closeComment: This issue has been automatically closed because there has been no response to our request for more information. Please reach out if you have or find the answers we need so that we can investigate further.
