# Configuration for support-requests - https://github.com/dessant/support-requests
supportLabel: invalid
supportComment: This issue tracker is for *confirmed bugs* and *approved feature requests* only. Please review the [Contribution Guidelines](https://github.com/red-eclipse/base/blob/master/.github/CONTRIBUTING.md) for this repository. Your post may be more appropriate in our 
[Discussion Area](http://redeclipse.net/discuss)
close: true
lock: true
