# Configuration for support-requests - https://github.com/dessant/support-requests
supportLabel: invalid
supportComment: This issue tracker is for **discussions** and **feature requests** only. Please review the [Contribution Guidelines](http://redeclipse.net/contribute). If you want to report a bug in the game or submit a pull request, you should use our [Issue Tracker](http://redeclipse.net/issues).
close: true
lock: true
